# Generated by Django 4.0.10 on 2023-07-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stock_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('ticker', 'owner'), name='unicidade'),
        ),
    ]
