# Generated by Django 4.0.10 on 2023-08-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stock_unicidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bottom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='period',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='stock',
            name='top',
            field=models.FloatField(default=10000.0),
        ),
    ]
